name: smart_fridge
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.19

  # Auth
  google_sign_in: ^6.2.1

  # UI
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.66.0

  # Internet
  http: ^1.6.0
  url_launcher: ^6.3.2
  internet_connection_checker: ^1.0.0+1

  # Utils
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  flutter_dotenv: ^6.0.0
  image_picker: ^1.0.7
  flutter_image_compress: ^2.3.0
  geolocator: ^11.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  share_plus: ^10.0.0
  app_links: ^7.0.0
  firebase_storage: ^11.7.7
  record: ^6.0.0
  audioplayers: ^6.5.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  purchases_flutter: ^8.11.0
  shared_preferences: ^2.5.4
  google_mobile_ads: ^7.0.0
  flutter_sound: ^9.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Ð“ÐµÐ½ÐµÑ€Ð°Ñ‚Ð¾Ñ€Ð¸
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - .env

# ðŸ‘‡ ÐžÐ¡Ð¬ Ð¢Ð£Ð¢ Ð‘Ð£Ð›Ð ÐŸÐžÐœÐ˜Ð›ÐšÐ. ÐœÐÐ„ Ð‘Ð£Ð¢Ð˜ flutter_launcher_icons:
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

# Ð—Ð°ÑÑ‚Ð°Ð²ÐºÐ°
flutter_native_splash:
  color: "#e8f5e9"
  image: "assets/logo.png"
  android_12:
    color: "#e8f5e9"
    image: "assets/logo.png"