name: smart_fridge
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.19

  # Auth
  google_sign_in: ^6.2.1

  # UI
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.66.0 # Ð“Ñ€Ð°Ñ„Ñ–ÐºÐ¸

  # Internet
  http: ^1.2.0
  url_launcher: ^6.2.5

  # Notifications
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # ðŸ‘‡ Ð“Ð•ÐÐ•Ð ÐÐ¢ÐžÐ Ð˜ Ð†ÐšÐžÐÐžÐš Ð¢Ð Ð—ÐÐ¡Ð¢ÐÐ’ÐšÐ˜
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  # ðŸ‘‡ Ð’ÐÐ–Ð›Ð˜Ð’Ðž: Ð’Ð†Ð”ÐšÐ Ð˜Ð’ÐÐ„ÐœÐž Ð”ÐžÐ¡Ð¢Ð£ÐŸ Ð”Ðž ÐšÐÐ Ð¢Ð˜ÐÐšÐ˜
  assets:
    - assets/logo.png

# --- ÐÐÐ›ÐÐ¨Ð¢Ð£Ð’ÐÐÐÐ¯ Ð†ÐšÐžÐÐšÐ˜ ---
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png" # Ð¨Ð»ÑÑ… Ð´Ð¾ Ñ‚Ð²Ð¾Ð³Ð¾ Ð»Ð¾Ð³Ð¾
  min_sdk_android: 21

# --- ÐÐÐ›ÐÐ¨Ð¢Ð£Ð’ÐÐÐÐ¯ Ð—ÐÐ¡Ð¢ÐÐ’ÐšÐ˜ (SPLASH) ---
flutter_native_splash:
  color: "#4CAF50" # Ð—ÐµÐ»ÐµÐ½Ð¸Ð¹ ÐºÐ¾Ð»Ñ–Ñ€ Ñ„Ð¾Ð½Ñƒ (ÑÐº Ñƒ Ñ‚Ð²Ð¾Ñ”Ð¼Ñƒ Ð´Ð¾Ð´Ð°Ñ‚ÐºÑƒ)
  image: "assets/logo.png" # Ð›Ð¾Ð³Ð¾Ñ‚Ð¸Ð¿ Ð¿Ð¾ Ñ†ÐµÐ½Ñ‚Ñ€Ñƒ
  android_12:
    color: "#4CAF50"
    image: "assets/logo.png"