name: smart_fridge
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.19

  # Ð’Ñ…Ñ–Ð´
  google_sign_in: ^6.2.1

  # Ð†Ð½Ñ‚ÐµÑ€Ñ„ÐµÐ¹Ñ
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0

  # Ð†Ð½Ñ‚ÐµÑ€Ð½ÐµÑ‚
  http: ^1.2.0
  url_launcher: ^6.2.5

  # ðŸ‘‡ ÐÐžÐ’Ð•: ÐÐ°Ð³Ð°Ð´ÑƒÐ²Ð°Ð½Ð½Ñ Ñ‚Ð° Ð§Ð°Ñ
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true